from __future__ import annotations
import pandas as pd
import streamlit as st


def render(repo, origin, fsas, data):
    st.header("Forecast Setup & Input Validation")
    st.info(
        "This public demo uses precomputed outputs generated by the frozen local pipeline. "
        "Changing the date/FSA selection and pressing **Run analysis** refreshes all dashboard views; it does not retrain or reload the 13 GB model bundle."
    )
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Forecast origin", pd.Timestamp(origin).strftime("%Y-%m-%d %H:%M"))
    c2.metric("Selected FSAs", len(fsas))
    c3.metric("Forecast horizons", data["horizon"].nunique())
    c4.metric("Prediction rows", len(data))

    st.subheader("Operational input contract")
    st.markdown(
        """
Before running the **local operational pipeline**, the following inputs must be preloaded:
- **Recent electricity demand:** at least 168 contiguous observed hours for each selected FSA.
- **Weather forecast / weather grid:** the forecast-origin and required future weather inputs used by the validated IFB contract.
- **Forecast origin/date:** selected only after both input sources pass validation.

The public Streamlit deployment intentionally exposes only already-validated forecast origins.
"""
    )
    st.subheader("Selected analysis preview")
    preview = data[["fsa","target_timestamp","horizon","forecast_consumption_kwh","peak_risk_score","peak_alert"]].copy()
    st.dataframe(preview, use_container_width=True, hide_index=True, height=360)
